apiVersion: v1
kind: Pod
metadata:
  name: bad-registry-pod
  labels:
    app: bad-registry
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: main
    image: gcr.io/google-containers/nginx:1.21
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false