apiVersion: v1
kind: Pod
metadata:
  name: latest-pod
  labels:
    app: latest
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: main
    image: nginx:latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false