apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  labels:
    app: resources
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: main
    image: docker.io/nginx:1.21
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false